apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-sa
  namespace: argo
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-workflow-templates-manager
rules:
- apiGroups:
    - argoproj.io
  resources:
    - workflows
    - workflowtemplates
    - clusterworkflowtemplates
    - cronworkflows
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-cluster-workflow-templates-manager
subjects:
- kind: ServiceAccount
  name: argo-workflows-sa
  namespace: argo
roleRef:
  kind: ClusterRole
  name: cluster-workflow-templates-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sa.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo-workflows-sa
type: kubernetes.io/service-account-token