apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: describe-ec2-resource
    image: 750876142122.dkr.ecr.ap-northeast-2.amazonaws.com/describe-ec2-resource:8c670c35dec413cd4f51e8c3d963663cd2b2980e