apiVersion: batch/v1
kind: CronJob
metadata:
  name: describe-resource-ec2-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName : cronjob-sa
          containers:
          - name: describe-ec2-resource
            image: 750876142122.dkr.ecr.ap-northeast-2.amazonaws.com/describe-ec2-resource:084cb8380b22f6d3bf16d75e2b1b5e0011ce4afb
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: parameter
            env:
            - name: PARAMETER_ACCOUNT
              value: ${{ .Values.PARAMETER_ACCOUNT }}
          restartPolicy: OnFailure