apiVersion: batch/v1
kind: CronJob
metadata:
  name: describe-resource-ec2-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName : cronjob-sa
          containers:
          - name: describe-ec2-resource
            image: 750876142122.dkr.ecr.ap-northeast-2.amazonaws.com/describe-ec2-resource:56662aa342f04f23fd0c1a49cd187c42dcdbc1b6
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: parameter
            env:
            - name: PARAMETER_ACCOUNT
              value: ${{ .Values.PARAMETER_ACCOUNT }}
          restartPolicy: OnFailure