apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflows-sa
  namespace: argo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::750876142122:role/argo-workflow-eks-project-prd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo
  name: pod-patch
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflows-sa-patch
  namespace: argo
subjects:
- kind: ServiceAccount
  name: workflows-sa
  namespace: argo
roleRef:
  kind: Role
  name: pod-patch
  apiGroup: rbac.authorization.k8s.io