kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-reader-binding
  namespace: vault-test
subjects:
- kind: ServiceAccount
  name: vault-secret-read
  namespace: vault-test
roleRef:
  kind: ClusterRole
  name: vault-reader
  apiGroup: rbac.authorization.k8s.io
