apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: my-secret-provider
spec:
  provider: aws
  secretObjects:
  - secretName: my-secret  # 쿠버네티스에서 생성하고 파드에 마운트 할 secret 네임
    type: Opaque
    data:
    - key: "test" # 시크릿에 주입할 키 (my-secret이라는 시크릿에 USERNAME 키와 그 값이 주입된다.)
      objectName: "test" # 볼륨에 마운트되어 있는 파일이름 (아래의 jmesPath/objectAlias)
    - key: "PASSWORD"
      objectName: "PASSWORD"
  parameters:
    region: ap-northeast-2
    objects: |
        - objectName: "eks/eks-project-prd"  # 2번에서 등록한 시크릿 네임
          objectType: "secretsmanager"
          jmesPath: 
            - path: "test" 
              objectAlias: "test"
            - path: "PASSWORD"
              objectAlias: "PASSWORD"
