{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" . }}
spec:
  schedule: "* * * * *"
  jobTemplate:
      spec:
        template:
          spec:
            serviceAccountName : {{ include "cronjob.serviceAccountName" . }}
            containers:
            - name: {{ .Values.cronjob.containerName }}
              image: {{ .Values.cronjob.image }}
              imagePullPolicy: IfNotPresent
              envFrom:
              - configMapRef:
                  name: parameter
            restartPolicy: OnFailure
{{- end }}
  
