name: ci
permissions:
  id-token: write
  contents: write
  pull-requests: write
on: 
  push:
    branches:
      - dev # main
env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: custodian-repo

jobs:
  custodian:
    runs-on: ubuntu-22.04
    environment: "describe-ec2-resource"
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login-ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true


      - name: Build and Push
        run: |
          ls -l
          docker build . --file ./features/tagging/custodian/Dockerfile --no-cache --tag ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Push the Docker image
        run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

  # - name: get-image-url
  #   id: get-image-url
  #   run: echo "image_url=750876142122.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_OUTPUT


  setup:
    runs-on: ubuntu-latest
    environment: "describe-ec2-resource"
    needs: custodian
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Retrieve items from DynamoDB
        id: set-matrix
        run: |
          items=$(aws dynamodb scan --table-name argoworkflows-test --query 'Items' --output yaml > items.yaml)
          cat items.yaml

          
          length=$(yq e 'length' items.yaml)
          echo "length : $length"
          matrix_values="["
          for i in $(seq 0 $(($length - 1))); do
            account=$(yq e ".[$i].account.S" items.yaml)
            bucket=$(yq e ".[$i].bucket.S" items.yaml)
            region=$(yq e ".[$i].region.S" items.yaml)
            role=$(yq e ".[$i].role.S" items.yaml)
            service=$(yq e ".[$i].service.S" items.yaml)
            profile=$(yq e ".[$i].profile.S" items.yaml)
            
            matrix_values="${matrix_values}{\"account\": \"$account\", \"bucket\": \"$bucket\", \"region\": \"$region\", \"role\": \"$role\", \"service\": \"$service\", \"profile\": \"$profile\"},"
          done
          matrix_values="${matrix_values%?}]"
          echo "matrix=$matrix_values" >> $GITHUB_OUTPUT

  process:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.terraform-setup.outcome}}
    strategy:
      matrix:
        item: ${{fromJson(needs.setup.outputs.matrix)}}
    environment: "describe-ec2-resource"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Process item
      #   run: |
      #     account=${{ matrix.item.account }}
      #     bucket=${{ matrix.item.bucket }}
      #     region=${{ matrix.item.region }}
      #     role=${{ matrix.item.role }}
      #     service=${{ matrix.item.service }}
      #     profile=${{ matrix.item.profile }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: aws sts assumerole
        run: |
          aws sts assume-role --role-arn "arn:aws:iam::${{ matrix.item.account }}:role/${{ matrix.item.role }}" --role-session-name ${{ matrix.item.profile }} --region ap-northeast-2 > sts.json
          access=$(cat sts.json  | yq '.Credentials.AccessKeyId')
          secret=$(cat sts.json  | yq '.Credentials.SecretAccessKey')
          sessiontoken=$(cat sts.json  | yq '.Credentials.SessionToken')
          echo "AWS_ACCESS_KEY_ID=$access" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$secret" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$sessiontoken" >> $GITHUB_ENV
          aws configure set aws_access_key_id $access --profile ${{ matrix.item.profile }}
          aws configure set aws_secret_access_key $secret --profile ${{ matrix.item.profile }}
          aws configure set aws_session_token $sessiontoken --profile ${{ matrix.item.profile }}

      - name: install terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: tf init
        id: terraform-setup
        run: |
          echo 
          cd ${GITHUB_WORKSPACE}/iac/terraform/custodian
          terraform init -backend-config="bucket=${{ matrix.item.bucket }}" -backend-config="key=${{ matrix.item.bucket }}/eks-project-custodian-dev.tfstate"
          terraform apply -var="aws_profile=${{ matrix.item.profile }}" -var="s3_bucket=${{ matrix.item.bucket }}" -var="key=${{ matrix.item.bucket }}/eks-project-custodian-dev.tfstate" -var="image_uri=750876142122.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" -auto-approve

  slack:
    runs-on: ubuntu-latest
    environment: "custodian"
    needs: process
    if: always()
    steps:
    - name: slack
      uses: slackapi/slack-github-action@v1.24.0
      id: slack
      with:
        payload: |
          {
            "text": "custoidian deployment finished (${{ needs.process.outputs.result}})",
            "attachments": [
              {
                "pretext": "Deployment finished",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "${{ needs.process.outputs.result}}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

